[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.primary]
background = "#101010"
bright_foreground = "#eaeaea"
dim_foreground = "#828482"
foreground = "#a7d407"

[font]
size = 11.5

[font.bold]
family = "CodeNewRoman Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CodeNewRoman Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "CodeNewRoman Nerd Font"
style = "Italic"

[font.normal]
family = "CodeNewRoman Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 0

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 5
y = 5
